#!/bin/sh

DIR="$HOME/.config"
rofi_cmd="rofi -theme $DIR/rofi/themes/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Handle user choice
handle_choice() {
    ans=$(rofi -dmenu -i -no-fixed-num-lines -p "Are You Sure? : " -theme "$DIR"/rofi/themes/confirm.rasi)
    if [ "$ans" = "y" ]; then
        "$1"
    elif [ "$ans" = "n" ]; then
        exit
    else
        rofi -theme "$DIR"/rofi/themes/askpass.rasi -e "Options  -  yes / y / no / n"
    fi
}

# Options
shutdown=""
reboot=""
hibernate="󰒲"
lock=""
suspend="󰤄"
logout="󰍃"

# Variable passed to rofi
options="$shutdown\n$reboot\n$hibernate\n$lock\n$suspend\n$logout"

chosen="$(printf "%b" "$options" | $rofi_cmd -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in
"$shutdown")
    handle_choice "systemctl poweroff"
    ;;
"$reboot")
    handle_choice "systemctl reboot"
    ;;
"$hibernate")
    handle_choice "systemctl hibernate"
    ;;
"$lock")
    i3lock -i ~/.config/rofi/script/material-ocean.png
    ;;
"$suspend")
    handle_choice "systemctl suspend"
    ;;
"$logout")
    handle_choice "i3-msg exit"
    ;;
esac

exit 0
